server:
  port: 7907

user:
  servicePath: http://localhost:7900/simple/
spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka
      enabled: true
      register-with-eureka: true
      fetch-registry: true
    healthcheck:
      enabled: true
instance:
  prefer-ip-address: true
management:
  endpoint:
    health:
      show-details: always
feign:
  # Dalston SR1（待定）之后的版本默认关闭hystrix对feign的支持，如果想要使用fallback功能这里必须启用
  hystrix:
    enabled: true