
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
      instance: microservice-discovery-eureka
    #prefer-ip-address: true
    #instance-id: 192.168.15.93
spring:
  security:
    user:
      name: user
      password: 123
