server:
  port: 8002

user:
  servicePath: http://microservice-provider-user:7900/simple/
spring:
  application:
    name: microservice-movie-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka
      enabled: true
      register-with-eureka: true
      fetch-registry: true
    healthcheck:
      enabled: true
instance:
  prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always